# Generated by Django 3.2.14 on 2022-11-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint', models.CharField(max_length=20)),
                ('response', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('replytime', models.CharField(max_length=20)),
                ('replydate', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'complaint',
                'managed': False,
            },
        ),
    ]
