# Generated by Django 3.2.14 on 2022-11-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('staffname', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=20)),
                ('salary_day', models.CharField(db_column='salary/day', max_length=20)),
                ('day_present', models.CharField(db_column='day present', max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'staff',
                'managed': False,
            },
        ),
    ]
