# Generated by Django 3.2.14 on 2022-11-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('n_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.DateField()),
            ],
            options={
                'db_table': 'notification',
                'managed': False,
            },
        ),
    ]
