# Generated by Django 3.2.14 on 2022-11-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('conditions', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('availability', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'bike',
                'managed': False,
            },
        ),
    ]
