# Generated by Django 3.2.14 on 2022-11-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('uaddress', models.CharField(max_length=20)),
                ('aadharnum', models.CharField(max_length=20)),
                ('licensenum', models.CharField(max_length=20)),
                ('pancardno', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=65)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
